name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          sudo apt update
          sudo apt install -y qtbase5-dev

      - run: qmake dirview.pro

      - run: make -j$(nproc)