name: Package

on:
  release:
    types: [published]

jobs:
  deb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          sudo apt update
          sudo apt install -y \
            debhelper \
            devscripts \
            qtbase5-dev \
            build-essential:native

      - run: dpkg-buildpackage -us -uc

      - uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ../*.deb